/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Product { 
    readonly id?: number;
    sku?: string;
    name?: string;
    price?: number | null;
    weight?: number | null;
    description?: string | null;
    stock?: number;
    subcategory?: Array<string>;
    media?: Array<string>;
    brand?: string | null;
    carts?: Array<string>;
}

